from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

from .rules import Rules, is_glob, mcp_parts

JsonRenderer = Callable[[Rules, dict[str, Any]], dict[str, Any]]
TextRenderer = Callable[[Rules], str]

HEADER_LINES = (
    "GENERATED by permissions/sync.py — do not edit.",
    "Edit permissions/permissions.toml and re-run permissions/sync.py.",
)

PI_SCHEMA = (
    "https://cdn.jsdelivr.net/npm/@gotgenes/"
    "pi-permission-system@23.0.0/schemas/permissions.schema.json"
)

CATEGORIES = ("allow", "deny", "ask")


@dataclass(frozen=True)
class JsonSpec:
    fn: JsonRenderer
    ensure_ascii: bool = False


@dataclass(frozen=True)
class TextSpec:
    fn: TextRenderer


# --------------------------------------------------------------------------
# claude — mcp-permissions.json: PermissionRequest hook policy, fully owned.
# --------------------------------------------------------------------------


def render_claude_mcp(rules: Rules, base: dict[str, Any]) -> dict[str, Any]:
    return {
        "allow": list(rules.mcp_allow),
        "ask": list(rules.mcp_ask),
        "deny": list(rules.mcp_deny),
    }


# --------------------------------------------------------------------------
# pi — pi/permissions.json, fully owned. Last-match-wins, so a pattern set by
# a later category is deleted and reinserted to move it to the end of the map.
# minimatch means `foo *` never matches a bare `foo`, so both forms are emitted.
# --------------------------------------------------------------------------


def pi_patterns(entry: str) -> list[str]:
    return [entry] if is_glob(entry) else [entry, f"{entry} *"]


def pi_mcp_patterns(entry: str) -> list[str]:
    server, tool = mcp_parts(entry)
    patterns = [f"{server}_{tool}", f"{server}:{tool}"]
    if tool == "*":
        patterns += [f"mcp_server_{server}", f"mcp_connect_{server}"]
    return patterns


def render_pi(rules: Rules, base: dict[str, Any]) -> dict[str, Any]:
    ordered = (("allow", "allow"), ("ask", "ask"), ("deny", "deny"))

    bash: dict[str, str] = {"*": "ask"}
    for category, decision in ordered:
        for entry in rules.shell(category):
            for pattern in pi_patterns(entry):
                bash.pop(pattern, None)
                bash[pattern] = decision

    mcp: dict[str, str] = {"*": "ask"}
    for category, decision in ordered:
        for entry in rules.mcp(category):
            for pattern in pi_mcp_patterns(entry):
                mcp.pop(pattern, None)
                mcp[pattern] = decision

    return {
        "$schema": PI_SCHEMA,
        "permission": {"*": "allow", "bash": bash, "mcp": mcp},
    }


RENDERERS: dict[str, JsonSpec | TextSpec] = {
    "claude-mcp": JsonSpec(render_claude_mcp, ensure_ascii=True),
    "pi": JsonSpec(render_pi),
}
