"""The generated OpenCode plugin and Pi extension.

These assert the *contract* of the generated source — what it subscribes to,
what it embeds, what it refuses to carry. That the emitted JavaScript actually
denies, mutates and distinguishes a crash from a block is proved by
`test_adapters_execute.py`, which runs it under node against real scripts.

Splitting them is deliberate: this file must stay green with no node installed,
so a string assertion here is never asked to stand in for a behaviour.
"""

from __future__ import annotations

import json
from typing import Any

import pytest

from loadout.adapters import (
    OPENCODE_MAPPINGS,
    PI_MAPPINGS,
    render_opencode_adapter,
    render_pi_adapter,
)
from loadout.hooks import CLAUDE_EVENTS

RENDERERS = (render_opencode_adapter, render_pi_adapter)


def cmd(command: str = "notify.sh") -> dict[str, Any]:
    return {"type": "command", "command": command, "timeout": 5}


DOCUMENT: dict[str, Any] = {
    "PreToolUse": [{"matcher": "Bash", "hooks": [cmd("guard.sh")]}],
    "PostToolUse": [{"hooks": [cmd()]}],
}


def embedded(source: str) -> dict[str, Any]:
    """The `const HOOKS = {…}` table, parsed back out of the generated file.

    `raw_decode` rather than a regex: it stops at the end of the object however
    the object is spelled, where a pattern anchored on a closing brace at the
    start of a line silently fails to match an empty `{}`.
    """
    marker = "const HOOKS = "
    start = source.find(marker)
    assert start != -1, "generated file has no HOOKS table"
    table, _ = json.JSONDecoder().raw_decode(source, start + len(marker))
    assert isinstance(table, dict)
    return table


# --- what reaches the file ---------------------------------------------------


@pytest.mark.parametrize("render", RENDERERS)
def test_the_document_is_embedded_verbatim(render: Any) -> None:
    """The ABI is Claude's protocol, so an adapter translates nothing on the way
    in. Anything else would mean two hook vocabularies to keep in step."""
    assert embedded(render(DOCUMENT)) == DOCUMENT


@pytest.mark.parametrize("render", RENDERERS)
def test_an_unmapped_event_is_named_and_not_embedded(render: Any) -> None:
    """Neither harness has a WorktreeCreate analogue. Leaving it in the table
    would put a hook in the file that silently never fires."""
    document = {**DOCUMENT, "WorktreeCreate": [{"hooks": [cmd()]}]}
    source = render(document)
    assert "WorktreeCreate" not in embedded(source)
    assert "// - WorktreeCreate" in source


@pytest.mark.parametrize("render", RENDERERS)
def test_a_prompt_hook_is_reported_rather_than_dropped_in_silence(render: Any) -> None:
    """A `prompt` hook has no command to spawn, so an adapter structurally
    cannot carry it. The user has to learn that from somewhere, and the file
    they would look in is this one."""
    document = {"PreToolUse": [{"hooks": [{"type": "prompt", "prompt": "check"}]}]}
    source = render(document)
    assert "// - PreToolUse: prompt" in source
    assert embedded(source) == {}


@pytest.mark.parametrize("render", RENDERERS)
def test_a_document_needing_nothing_still_renders_a_loadable_file(render: Any) -> None:
    """An empty subscription list is a valid plugin, not an error. Rendering
    nothing at all would leave a stale adapter from a previous sync in place."""
    source = render({})
    assert embedded(source) == {}
    assert "Generated by loadout" in source


# --- subscriptions -----------------------------------------------------------


def test_opencode_subscribes_only_to_events_the_document_uses() -> None:
    source = render_opencode_adapter({"PreToolUse": [{"hooks": [cmd()]}]})
    assert '"tool.execute.before"' in source
    assert '"tool.execute.after"' not in source


def test_pi_subscribes_only_to_events_the_document_uses() -> None:
    source = render_pi_adapter({"SessionEnd": [{"hooks": [cmd()]}]})
    assert 'pi.on("session_shutdown"' in source
    assert 'pi.on("tool_call"' not in source


def test_opencode_reads_tool_input_from_the_output_parameter() -> None:
    """`tool.execute.before`'s `input` is `{tool, sessionID, callID}` and carries
    no arguments — they live only on `output.args`. Reading `input.args` would
    hand every hook an undefined `tool_input` and look correct."""
    source = render_opencode_adapter({"PreToolUse": [{"hooks": [cmd()]}]})
    assert "tool_input: output.args," in source


def test_pi_is_told_the_session_file_rather_than_a_run_mode() -> None:
    """Pi's `ctx.mode` is `"tui" | "rpc" | "json" | "print"` — a run mode. Naming
    it `permission_mode` would hand a hook something that reads like a permission
    posture and is not, so the field is omitted instead."""
    source = render_pi_adapter({"PreToolUse": [{"hooks": [cmd()]}]})
    assert "transcript_path: ctx.sessionManager.getSessionFile()," in source
    assert "permission_mode" not in source


def test_opencode_omits_the_two_fields_it_has_no_source_for() -> None:
    """Spec 4b-i open question 3, answered no. A fabricated `"default"` is worse
    than an absent field: a hook that relaxes on it would relax on a guess."""
    source = render_opencode_adapter({"PreToolUse": [{"hooks": [cmd()]}]})
    assert "permission_mode" not in source
    assert "transcript_path" not in source


# --- the mapping table -------------------------------------------------------


@pytest.mark.parametrize("mappings", (OPENCODE_MAPPINGS, PI_MAPPINGS))
def test_every_mapping_names_a_real_abi_event(mappings: Any) -> None:
    """A mapping for an event Claude does not define could never fire, and would
    be indistinguishable from one that simply has not been reached yet."""
    assert {m.event for m in mappings} <= CLAUDE_EVENTS


@pytest.mark.parametrize("mappings", (OPENCODE_MAPPINGS, PI_MAPPINGS))
def test_every_mapping_records_what_would_exercise_it(mappings: Any) -> None:
    """Spec 4b-i Decision 4. A branch can be correct, tested and unreachable, and
    nothing fails when it becomes so — `pi-moves-key` did exactly that. The
    defence is a named condition a later reader can check the *possibility* of,
    which is answerable, rather than the code's correctness, which is not."""
    for mapping in mappings:
        assert mapping.reaches.strip(), f"{mapping.event}: no reachability condition"


@pytest.mark.parametrize("mappings", (OPENCODE_MAPPINGS, PI_MAPPINGS))
def test_no_event_is_mapped_twice(mappings: Any) -> None:
    events = [m.event for m in mappings]
    assert len(events) == len(set(events))
