from __future__ import annotations

from pathlib import PurePosixPath

from loadout.targets import HEADER, TARGETS


def test_header_is_byte_exact() -> None:
    assert HEADER == (
        "<!-- GENERATED by loadout — do not edit. "
        "Edit the fragments in global/fragments/ and re-run `loadout sync`. -->"
    )


def test_three_targets_with_unique_paths() -> None:
    paths = [t.path for t in TARGETS]
    assert len(paths) == 3
    assert len(set(paths)) == 3


def test_one_source_maps_to_three_destinations() -> None:
    shared = next(t for t in TARGETS if t.path == PurePosixPath("global/AGENTS.md"))
    assert shared.destinations == (
        PurePosixPath("~/.codex/AGENTS.md"),
        PurePosixPath("~/.gemini/GEMINI.md"),
        PurePosixPath("~/.pi/agent/AGENTS.md"),
    )


def test_two_sources_share_one_destination_via_profile() -> None:
    claude = [t for t in TARGETS if t.destinations == (PurePosixPath("~/.claude/CLAUDE.md"),)]
    assert len(claude) == 2
    assert sorted(t.profile or "default" for t in claude) == ["autonomous", "default"]


def test_autonomous_target_swaps_only_the_git_policy_fragment() -> None:
    by_profile = {t.profile: t for t in TARGETS if t.destinations[0].name == "CLAUDE.md"}
    default, autonomous = by_profile[None], by_profile["autonomous"]
    assert "git-policy" in default.fragments
    assert "git-policy.autonomous" in autonomous.fragments
    assert [f for f in default.fragments if not f.startswith("git-policy")] == [
        f for f in autonomous.fragments if not f.startswith("git-policy")
    ]
