from __future__ import annotations

import tomllib
from pathlib import Path

from loadout.permissions.renderers import render_codex_config
from loadout.permissions.rules import EMPTY_RULES, Rules, parse_rules
from loadout.servers import parse_servers

FIXTURES = Path(__file__).parent / "fixtures"


def _rules() -> Rules:
    return parse_rules(FIXTURES / "permissions.toml")


def _servers(tmp_path: Path, body: str) -> dict[str, object]:
    source = tmp_path / "mcp.toml"
    source.write_text(body, encoding="utf-8")
    return dict(parse_servers(source))


def test_definition_and_policy_share_one_table(tmp_path: Path) -> None:
    """The reason this renderer exists. Codex keys both off `[mcp_servers.<name>]`,
    so emitting them from two slices declares the table twice and Codex refuses to
    parse its own config — a failure that reaches the user as a dead harness, not
    as a loadout error.
    """
    body = 'transport = "stdio"\ncommand = "svc-bin"\nargs = ["--serve"]\n'
    rendered = render_codex_config(_rules(), _servers(tmp_path, f"[svc]\n{body}"))

    assert rendered.count("[mcp_servers.svc]\n") == 1
    svc = tomllib.loads(rendered)["mcp_servers"]["svc"]
    assert svc["command"] == "svc-bin"
    assert svc["default_tools_approval_mode"] == "approve"


def test_env_and_policy_coexist_on_one_server(tmp_path: Path) -> None:
    """A sub-table and a scalar from different sources land on the same server.

    This does *not* pin insertion order: tomlkit emits a table's scalars ahead of
    its sub-tables regardless, which a mutation swapping the two confirmed. The
    ordering hazard is real only where fragments are assembled as text, and
    `test_surgery` pins it there.
    """
    body = 'transport = "stdio"\ncommand = "svc-bin"\nenv = { TOKEN_VAR = "SVC_TOKEN" }\n'
    rendered = render_codex_config(_rules(), _servers(tmp_path, f"[svc]\n{body}"))

    svc = tomllib.loads(rendered)["mcp_servers"]["svc"]
    assert svc["default_tools_approval_mode"] == "approve"
    assert svc["env"] == {"TOKEN_VAR": "SVC_TOKEN"}


def test_a_server_with_no_policy_still_renders(tmp_path: Path) -> None:
    body = 'transport = "http"\nurl = "https://jina.example"\nauth_env_var = "JINA_KEY"\n'
    rendered = render_codex_config(_rules(), _servers(tmp_path, f"[jina]\n{body}"))

    jina = tomllib.loads(rendered)["mcp_servers"]["jina"]
    assert jina == {"url": "https://jina.example", "bearer_token_env_var": "JINA_KEY"}


def test_policy_for_a_server_defined_elsewhere_still_applies(tmp_path: Path) -> None:
    """A server Codex knows about by other means still takes loadout's policy."""
    rendered = render_codex_config(_rules(), {})

    assert tomllib.loads(rendered)["mcp_servers"]["blocked"] == {"enabled": False}


def test_no_servers_and_no_policy_is_a_header_alone() -> None:
    rendered = render_codex_config(EMPTY_RULES, {})

    assert tomllib.loads(rendered) == {}
    assert rendered.startswith("# Generated by loadout")
