from __future__ import annotations

import json
import subprocess
from pathlib import Path

import loadout
from loadout.commands import _DIFF_LIMIT
from loadout.written import normalise as _normalise
from loadout.written import written_state_path


def _git(root: Path, *args: str) -> None:
    subprocess.run(
        [
            "git",
            "-C",
            str(root),
            "-c",
            "user.email=test@example.com",
            "-c",
            "user.name=test",
            "-c",
            "commit.gpgsign=false",
            "-c",
            "init.defaultBranch=main",
            *args,
        ],
        check=True,
        capture_output=True,
    )


def _commit_source(root: Path) -> None:
    _git(root, "init", "-q")
    _git(root, "add", "-A")
    _git(root, "commit", "-qm", "source")


def _adopt(root: Path) -> None:
    """Commit the source and take over the files another writer already owns."""
    _commit_source(root)
    assert loadout.main(["sync", "--root", str(root), "--force"]) == 0


def test_first_sync_warns_before_taking_over_another_writer_s_file(root: Path, capsys) -> None:
    """opencode.json exists before loadout ever runs — the fixture seeds mcp/sync.py's key.

    Adoption is the one time loadout is about to overwrite a file it has not written, so
    the warning is correct: look at it, then pass --force once.
    """
    _commit_source(root)
    assert loadout.main(["sync", "--root", str(root)]) == 1
    assert "perm/opencode.json was modified outside loadout" in capsys.readouterr().err


def test_a_reworded_banner_is_not_a_hand_edit(root: Path, capsys) -> None:
    """The banner is loadout's own text, so changing it is not evidence a user
    touched the file. Without this, rewording it makes every generated file on
    disk differ from every acceptable variant at once and the guard reports the
    whole tree as hand-edited — which it did, on 205 files."""
    _adopt(root)
    output = root / "out" / "shared.md"
    body = output.read_text(encoding="utf-8").split("\n", 1)[1]
    output.write_text(
        "<!-- GENERATED by loadout — do not edit. Edit the fragments and re-run. -->\n" + body,
        encoding="utf-8",
    )
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root)]) == 0
    assert "modified outside loadout" not in capsys.readouterr().err


def test_the_normaliser_strips_a_slash_slash_banner_too(root: Path) -> None:
    """The generated hook adapters are JavaScript and TypeScript, so their banner
    is `//`. A stripper knowing only `#` and `<!--` would leave it in the compared
    text and reintroduce the whole-tree false positive for exactly those files —
    the failure this normaliser exists to prevent, reappearing where it is least
    expected because every other generated file comments differently.
    """
    banner = "// Generated by loadout from hooks/*.json.\n"
    consequence = "// Edits to this file are replaced on the next sync.\n"
    body = "const HOOKS = {}\n"
    plugin = root / "loadout-hooks.js"

    assert _normalise(plugin, banner + consequence + body) == _normalise(
        plugin, "// Generated by loadout — do not edit.\n" + body
    )


def test_adding_a_banner_to_a_file_without_one_is_not_a_hand_edit(root: Path, capsys) -> None:
    """Stripping the banner leaves the blank line that separated it, so a file
    with no banner and one with a banner still differ by an interior blank —
    which `.strip()` cannot reach. Without collapsing the run, adopting a file
    another writer produced reports as a hand edit forever."""
    _adopt(root)
    output = root / "out" / "shared.md"
    body = output.read_text(encoding="utf-8").split("\n", 2)[2].lstrip("\n")
    output.write_text(body, encoding="utf-8")
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root)]) == 0
    assert "modified outside loadout" not in capsys.readouterr().err


def test_hand_edited_output_blocks_sync(root: Path, capsys) -> None:
    _adopt(root)
    output = root / "out" / "shared.md"
    output.write_text(output.read_text() + "\nhand-written line\n", encoding="utf-8")
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root)]) == 1
    err = capsys.readouterr().err
    assert "out/shared.md was modified outside loadout" in err
    assert output.read_text().endswith("hand-written line\n")


def test_the_warning_names_what_would_be_lost(root: Path, capsys) -> None:
    """A harness granting itself a permission at runtime must be named, not just counted."""
    _adopt(root)
    settings = root / "perm" / "claude.json"
    granted = '      "Bash(terraform apply:*)",\n'
    settings.write_text(
        settings.read_text().replace('    "allow": [\n', '    "allow": [\n' + granted, 1),
        encoding="utf-8",
    )
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root)]) == 1
    err = capsys.readouterr().err
    assert '-      "Bash(terraform apply:*)",' in err
    assert "would be lost" in err


def test_a_truncated_abort_still_names_the_complete_diff(root: Path, capsys) -> None:
    _adopt(root)
    # Comfortably more lines than _DIFF_LIMIT on their own, so the note appears
    # whatever the rendered document happens to be.
    bulk = {f"key-{index}": index for index in range(60)}
    (root / "perm" / "opencode.json").write_text(
        json.dumps(bulk, indent=2) + "\n", encoding="utf-8"
    )
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root)]) == 1
    err = capsys.readouterr().err
    assert "more line(s)" in err

    # The terminal shortens it; the file must not. A blocking prompt the reader
    # cannot see all of is one they learn to skip, and skipping this one means
    # reaching for --force — the thing the guard exists to prevent.
    path = Path(err.rsplit("The complete diff is at ", 1)[1].strip())
    assert path.is_file()
    assert len(path.read_text(encoding="utf-8").splitlines()) > _DIFF_LIMIT


def test_force_overwrites_a_file_modified_outside_loadout(root: Path, capsys) -> None:
    _adopt(root)
    output = root / "out" / "shared.md"
    output.write_text("clobber me\n", encoding="utf-8")
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root), "--force"]) == 0
    assert output.read_text().startswith("<!-- Generated by loadout")


def test_unsynced_source_edit_does_not_block(root: Path, capsys) -> None:
    _adopt(root)
    fragment = root / "instructions" / "shared.md"
    fragment.write_text(fragment.read_text() + "\nA freshly written sentence.\n", encoding="utf-8")
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root)]) == 0
    assert "A freshly written sentence." in (root / "out" / "shared.md").read_text()


def test_source_edit_that_was_already_synced_does_not_block(root: Path, capsys) -> None:
    """The routine workflow: edit a fragment, sync, read the diff, then sync again.

    After the first sync the outputs match the working render and no longer the
    committed one, so a committed-only baseline would report every file as modified.
    """
    _adopt(root)
    fragment = root / "instructions" / "shared.md"
    fragment.write_text(fragment.read_text() + "\nA freshly written sentence.\n", encoding="utf-8")
    assert loadout.main(["sync", "--root", str(root)]) == 0
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root)]) == 0
    assert "modified outside loadout" not in capsys.readouterr().err


def test_reordered_json_keys_do_not_block(root: Path, capsys) -> None:
    """A co-owning harness rewriting its own config reorders keys loadout owns."""
    _adopt(root)
    settings = root / "perm" / "claude.json"
    generated = settings.read_text()
    document = json.loads(generated)
    reordered = json.dumps({k: document[k] for k in reversed(list(document))}, indent=2)
    assert reordered != generated
    settings.write_text(reordered, encoding="utf-8")
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root)]) == 0
    assert "modified outside loadout" not in capsys.readouterr().err


def test_profile_switch_does_not_block(root: Path, fake_home: Path, capsys) -> None:
    """Both instruction targets share ~/.harness-a/PRIMARY.md, one per profile."""
    _commit_source(root)
    assert loadout.main(["sync", "--root", str(root), "--profile", "variant", "--force"]) == 0
    destination = fake_home / ".harness-a" / "PRIMARY.md"
    under_variant = destination.read_text()
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root)]) == 0
    assert "modified outside loadout" not in capsys.readouterr().err
    assert destination.read_text() != under_variant


def test_reverting_a_synced_source_edit_no_longer_blocks(root: Path, capsys) -> None:
    """Was "the honest limit of a stateless accept set" until the record existed.

    The output was written from a source state that was never committed and no longer
    exists in the working tree, so it matches neither render. It matches what sync
    recorded writing, which is the whole point of recording it.
    """
    _adopt(root)
    fragment = root / "instructions" / "shared.md"
    original = fragment.read_text()
    fragment.write_text(original + "\nA sentence I will take back.\n", encoding="utf-8")
    assert loadout.main(["sync", "--root", str(root)]) == 0
    # The loser, present before the final sync: without this the assertion below
    # passes against a build where the sentence was never written at all.
    assert "A sentence I will take back." in (root / "out" / "shared.md").read_text()
    fragment.write_text(original, encoding="utf-8")
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root)]) == 0
    assert "A sentence I will take back." not in (root / "out" / "shared.md").read_text()


def test_editing_a_source_twice_before_committing_does_not_block(root: Path, capsys) -> None:
    """The case ADR 0008 did not enumerate, and the one that actually bit.

    Edit, sync, edit again, sync — an ordinary loop with a commit at the end. The
    output on disk is rendered from a state that is neither HEAD nor the working
    tree, so before the record this aborted and sent the user to --force.
    """
    _adopt(root)
    fragment = root / "instructions" / "shared.md"
    original = fragment.read_text()
    fragment.write_text(original + "\nEdit A.\n", encoding="utf-8")
    assert loadout.main(["sync", "--root", str(root)]) == 0
    assert "Edit A." in (root / "out" / "shared.md").read_text()

    fragment.write_text(original + "\nEdit A.\nEdit B.\n", encoding="utf-8")
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root)]) == 0
    written = (root / "out" / "shared.md").read_text()
    assert "Edit A." in written and "Edit B." in written


def test_two_sources_feeding_one_destination_do_not_block(root: Path) -> None:
    """The live failure: with two inputs composing into one file you need not edit
    the same source twice. Edit one, sync, edit the other, and the output is a cross
    of committed and working state that neither render produces."""
    _adopt(root)
    first = root / "settings" / "claude.json"
    second = root / "settings" / "claude-afk.json"
    first.write_text(json.dumps({"model": "one"}) + "\n", encoding="utf-8")
    assert loadout.main(["sync", "--root", str(root)]) == 0
    assert "one" in (root / "perm" / "claude-empty.json").read_text()

    second.write_text(json.dumps({"effortLevel": "high"}) + "\n", encoding="utf-8")

    assert loadout.main(["sync", "--root", str(root)]) == 0
    document = json.loads((root / "perm" / "claude-empty.json").read_text())
    assert document["model"] == "one"
    assert document["effortLevel"] == "high"


def test_without_a_record_the_revert_blocks_exactly_as_before(root: Path, capsys) -> None:
    """Degradation is the property that makes this safe to ship: delete the record
    and the guard is the two-variant one, warning included."""
    _adopt(root)
    fragment = root / "instructions" / "shared.md"
    original = fragment.read_text()
    fragment.write_text(original + "\nTaken back.\n", encoding="utf-8")
    assert loadout.main(["sync", "--root", str(root)]) == 0
    fragment.write_text(original, encoding="utf-8")
    written_state_path(root).unlink()
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root)]) == 1
    assert "out/shared.md was modified outside loadout" in capsys.readouterr().err


def test_force_records_what_it_wrote(root: Path) -> None:
    """Otherwise a forced sync leaves no baseline and the next ordinary sync aborts
    again — which is how a copied file's --force became permanent rather than final."""
    _commit_source(root)
    assert not written_state_path(root).is_file()

    assert loadout.main(["sync", "--root", str(root), "--force"]) == 0

    assert written_state_path(root).is_file()


def test_check_records_nothing(root: Path) -> None:
    """`check` is read-only, and a record written by it would assert loadout wrote
    bytes it never wrote."""
    _commit_source(root)

    loadout.main(["check", "--root", str(root)])

    assert not written_state_path(root).is_file()


def test_no_committed_baseline_skips_the_check(root: Path, capsys) -> None:
    """Without a committed render, an unsynced source edit looks exactly like a hand edit."""
    assert loadout.main(["sync", "--root", str(root)]) == 0
    output = root / "out" / "shared.md"
    output.write_text("hand-written\n", encoding="utf-8")
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root)]) == 0
    err = capsys.readouterr().err
    assert "no committed baseline" in err
    assert output.read_text().startswith("<!-- Generated by loadout")


def test_editing_a_copied_supporting_file_twice_does_not_block(project: Path) -> None:
    """The permanent deadlock, now a regression test.

    A skill's supporting file is copied, not rendered, and that branch never consulted
    the accept set at all — it compared the destination against the *current* source.
    So the first edit blocked every later sync, and committing did not help, because
    HEAD was never consulted either. `--force` was the only exit, every time.
    """
    _adopt(project)
    reference = project / "loadout" / "skills" / "probe" / "reference.md"
    copy = project / ".claude" / "skills" / "probe" / "reference.md"

    reference.write_text("first edit\n", encoding="utf-8")
    assert loadout.main(["sync", "--root", str(project)]) == 0
    # The loser: the first edit provably reached the destination before the second.
    assert copy.read_text() == "first edit\n"

    reference.write_text("second edit\n", encoding="utf-8")

    assert loadout.main(["sync", "--root", str(project)]) == 0
    assert copy.read_text() == "second edit\n"


def test_a_hand_edited_copy_still_blocks(project: Path, capsys) -> None:
    """The record widens acceptance; it must not open it. Bytes that match neither the
    source nor anything sync wrote are still someone else's edit."""
    _adopt(project)
    copy = project / ".claude" / "skills" / "probe" / "reference.md"
    copy.write_text("typed straight into the destination\n", encoding="utf-8")
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(project)]) == 1
    assert "was modified outside loadout" in capsys.readouterr().err


def test_without_a_record_the_copied_edit_blocks_as_before(project: Path, capsys) -> None:
    _adopt(project)
    (project / "loadout" / "skills" / "probe" / "reference.md").write_text(
        "edited\n", encoding="utf-8"
    )
    written_state_path(project).unlink()
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(project)]) == 1
    assert "was modified outside loadout" in capsys.readouterr().err
