from __future__ import annotations

import json
import subprocess
from pathlib import Path

import loadout


def _git(root: Path, *args: str) -> None:
    subprocess.run(
        [
            "git",
            "-C",
            str(root),
            "-c",
            "user.email=test@example.com",
            "-c",
            "user.name=test",
            "-c",
            "commit.gpgsign=false",
            "-c",
            "init.defaultBranch=main",
            *args,
        ],
        check=True,
        capture_output=True,
    )


def _commit_source(root: Path) -> None:
    _git(root, "init", "-q")
    _git(root, "add", "-A")
    _git(root, "commit", "-qm", "source")


def _adopt(root: Path) -> None:
    """Commit the source and take over the files another writer already owns."""
    _commit_source(root)
    assert loadout.main(["sync", "--root", str(root), "--force"]) == 0


def test_first_sync_warns_before_taking_over_another_writer_s_file(root: Path, capsys) -> None:
    """opencode.json exists before loadout ever runs — the fixture seeds mcp/sync.py's key.

    Adoption is the one time loadout is about to overwrite a file it has not written, so
    the warning is correct: look at it, then pass --force once.
    """
    _commit_source(root)
    assert loadout.main(["sync", "--root", str(root)]) == 1
    assert "perm/opencode.json was modified outside loadout" in capsys.readouterr().err


def test_hand_edited_output_blocks_sync(root: Path, capsys) -> None:
    _adopt(root)
    output = root / "out" / "shared.md"
    output.write_text(output.read_text() + "\nhand-written line\n", encoding="utf-8")
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root)]) == 1
    err = capsys.readouterr().err
    assert "out/shared.md was modified outside loadout" in err
    assert output.read_text().endswith("hand-written line\n")


def test_the_warning_names_what_would_be_lost(root: Path, capsys) -> None:
    """A harness granting itself a permission at runtime must be named, not just counted."""
    _adopt(root)
    settings = root / "perm" / "claude.json"
    granted = '      "Bash(terraform apply:*)",\n'
    settings.write_text(
        settings.read_text().replace('    "allow": [\n', '    "allow": [\n' + granted, 1),
        encoding="utf-8",
    )
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root)]) == 1
    err = capsys.readouterr().err
    assert '-      "Bash(terraform apply:*)",' in err
    assert "would be lost" in err


def test_a_wholesale_rewrite_reports_how_much_it_truncated(root: Path, capsys) -> None:
    _adopt(root)
    # Comfortably more lines than _DIFF_LIMIT on their own, so the note appears
    # whatever the rendered document happens to be.
    bulk = {f"key-{index}": index for index in range(60)}
    (root / "perm" / "opencode.json").write_text(
        json.dumps(bulk, indent=2) + "\n", encoding="utf-8"
    )
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root)]) == 1
    assert "more diff line(s)" in capsys.readouterr().err


def test_force_overwrites_a_file_modified_outside_loadout(root: Path, capsys) -> None:
    _adopt(root)
    output = root / "out" / "shared.md"
    output.write_text("clobber me\n", encoding="utf-8")
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root), "--force"]) == 0
    assert output.read_text().startswith("<!-- Generated by loadout")


def test_unsynced_source_edit_does_not_block(root: Path, capsys) -> None:
    _adopt(root)
    fragment = root / "instructions" / "shared.md"
    fragment.write_text(fragment.read_text() + "\nA freshly written sentence.\n", encoding="utf-8")
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root)]) == 0
    assert "A freshly written sentence." in (root / "out" / "shared.md").read_text()


def test_source_edit_that_was_already_synced_does_not_block(root: Path, capsys) -> None:
    """The routine workflow: edit a fragment, sync, read the diff, then sync again.

    After the first sync the outputs match the working render and no longer the
    committed one, so a committed-only baseline would report every file as modified.
    """
    _adopt(root)
    fragment = root / "instructions" / "shared.md"
    fragment.write_text(fragment.read_text() + "\nA freshly written sentence.\n", encoding="utf-8")
    assert loadout.main(["sync", "--root", str(root)]) == 0
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root)]) == 0
    assert "modified outside loadout" not in capsys.readouterr().err


def test_reordered_json_keys_do_not_block(root: Path, capsys) -> None:
    """A co-owning harness rewriting its own config reorders keys loadout owns."""
    _adopt(root)
    settings = root / "perm" / "claude.json"
    generated = settings.read_text()
    document = json.loads(generated)
    reordered = json.dumps({k: document[k] for k in reversed(list(document))}, indent=2)
    assert reordered != generated
    settings.write_text(reordered, encoding="utf-8")
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root)]) == 0
    assert "modified outside loadout" not in capsys.readouterr().err


def test_profile_switch_does_not_block(root: Path, fake_home: Path, capsys) -> None:
    """Both instruction targets share ~/.harness-a/PRIMARY.md, one per profile."""
    _commit_source(root)
    assert loadout.main(["sync", "--root", str(root), "--profile", "variant", "--force"]) == 0
    destination = fake_home / ".harness-a" / "PRIMARY.md"
    under_variant = destination.read_text()
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root)]) == 0
    assert "modified outside loadout" not in capsys.readouterr().err
    assert destination.read_text() != under_variant


def test_reverting_a_synced_source_edit_blocks(root: Path, capsys) -> None:
    """The honest limit of a stateless accept set.

    Outputs written from a source state that was never committed, and no longer exists
    in the working tree, match neither baseline. --force resolves it and loses nothing,
    since the rewrite comes from the reverted source.
    """
    _adopt(root)
    fragment = root / "instructions" / "shared.md"
    original = fragment.read_text()
    fragment.write_text(original + "\nA sentence I will take back.\n", encoding="utf-8")
    assert loadout.main(["sync", "--root", str(root)]) == 0
    fragment.write_text(original, encoding="utf-8")
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root)]) == 1
    assert "out/shared.md was modified outside loadout" in capsys.readouterr().err
    assert loadout.main(["sync", "--root", str(root), "--force"]) == 0
    assert "A sentence I will take back." not in (root / "out" / "shared.md").read_text()


def test_no_committed_baseline_skips_the_check(root: Path, capsys) -> None:
    """Without a committed render, an unsynced source edit looks exactly like a hand edit."""
    assert loadout.main(["sync", "--root", str(root)]) == 0
    output = root / "out" / "shared.md"
    output.write_text("hand-written\n", encoding="utf-8")
    capsys.readouterr()

    assert loadout.main(["sync", "--root", str(root)]) == 0
    err = capsys.readouterr().err
    assert "no committed baseline" in err
    assert output.read_text().startswith("<!-- Generated by loadout")
