from __future__ import annotations

import difflib
import io
import json
import re
import subprocess
import sys
import tarfile
import tempfile
from collections.abc import Iterable
from pathlib import Path

from .emit import (
    Copied,
    check_all,
    collect_notices,
    declared_profiles,
    describe_file,
    render_all,
    write_all,
)
from .errors import LoadoutError
from .machine import machine_config_path
from .manifest import MANIFEST_NAME, InstructionTarget, load_manifest, manifest_path
from .project import (
    PROJECT_CONFIG_NAME,
    PROJECT_DIR,
    load_project_config,
    project_config_path,
)
from .resolve import resolve_fragment, resolve_item
from .scaffold import add_harness, init_global, init_project
from .templates import (
    TEMPLATES,
    VENDORED,
    copy_tree,
    declare,
    declared_sources,
    record_hash,
    resolve_template,
    template_divergence,
    template_files,
    tree_hash,
    unverifiable_templates,
    vendored_path,
)

_DIFF_LIMIT = 40


def cmd_init(root: Path, harnesses: tuple[str, ...]) -> int:
    for action in init_project(root, harnesses, machine_config_path=machine_config_path()):
        print(action)
    print("\nEdit loadout/permissions.toml, then run `loadout sync`.")
    return 0


def cmd_init_global(source: Path | None, force: bool = False) -> int:
    if source is None:
        if not sys.stdin.isatty():
            raise LoadoutError(
                "--source is required when not attached to a terminal "
                "(loadout init --global --source <path>)"
            )
        default = Path.home() / "loadout"
        response = input(f"Directory to hold the global loadout source [{default}]: ").strip()
        source = Path(response) if response else default
    for action in init_global(source.expanduser(), machine_config_path(), force=force):
        print(action)
    return 0


def cmd_harness_add(root: Path, harness: str) -> int:
    for action in add_harness(root, harness):
        print(action)
    return 0


def _display(path: Path, root: Path) -> str:
    """A destination may live outside root (e.g. under ~); relative_to() would raise."""
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)


# Case-insensitive because the banner has been both `GENERATED` and `Generated`;
# a normaliser that only knows the current spelling fails exactly when it is
# needed, which is the sync that changes the spelling.
# `//` is here for the generated hook adapters, which are JavaScript and
# TypeScript. Every other generated file comments with `#` or `<!--`, so a
# comment marker this did not know would leave the banner in the compared text
# and reintroduce the whole-tree false positive for exactly those two files.
_BANNER_LINE = re.compile(
    r"^\s*(?:<!--\s*|#\s*|//\s*)generated by loadout\b.*$", re.MULTILINE | re.IGNORECASE
)
_BLANK_RUN = re.compile(r"\n{3,}")
_BANNER_CONTINUATION = re.compile(
    r"^\s*(?:#|//)\s*edits? to this file are replaced.*$"
    r"|^\s*(?:#|//)\s*edit permissions\.toml\b.*$",
    re.MULTILINE | re.IGNORECASE,
)


def _normalise(path: Path, content: str) -> str:
    """Key order is load-bearing in output, but not in the question 'who wrote this?'.

    Claude Code rewrites its own settings.json and reorders keys loadout owns; comparing
    the parsed document keeps that from reading as a hand edit.

    The banner comes out for the same reason. It is loadout's own text, so rewording it
    is not evidence a user touched the file — but without this, changing it makes every
    generated file on disk differ from every acceptable variant at once, and the guard
    reports the whole tree as hand-edited. It did, on 205 files.
    """
    if path.suffix != ".json":
        stripped = _BANNER_CONTINUATION.sub("", _BANNER_LINE.sub("", content))
        # Removing the banner leaves the blank line that separated it, so a file
        # with no banner and one with a banner still differ by an interior blank
        # — which `.strip()` cannot reach. Collapsing runs is what makes the two
        # actually compare equal, and without it the guard reports a banner-only
        # difference as a hand edit. It did, on the one skill that carries a
        # `::: opencode` section.
        return _BLANK_RUN.sub("\n\n", stripped).strip()
    try:
        return json.dumps(json.loads(content), sort_keys=True)
    except json.JSONDecodeError:
        return content


def _render_variants(
    source_root: Path, profiles: Iterable[str], rebase_to: Path
) -> dict[Path, set[str]]:
    variants: dict[Path, set[str]] = {}
    for profile in profiles:
        try:
            rendered = render_all(source_root, profile)
        except LoadoutError:
            continue
        for path, content in rendered.items():
            if isinstance(content, Copied):
                continue  # verbatim by definition, so it has no per-profile form to vary
            try:
                key = rebase_to / path.relative_to(source_root)
            except ValueError:
                key = path  # a destination outside the root renders to the same path
            variants.setdefault(key, set()).add(_normalise(key, content))
    return variants


def _committed_variants(root: Path, profiles: Iterable[str]) -> dict[Path, set[str]]:
    try:
        proc = subprocess.run(
            ["git", "-C", str(root), "archive", "HEAD"], capture_output=True, check=False
        )
    except OSError:
        return {}
    if proc.returncode != 0:
        return {}
    with tempfile.TemporaryDirectory() as tmp_dir:
        try:
            with tarfile.open(fileobj=io.BytesIO(proc.stdout), mode="r:") as tar:
                tar.extractall(path=tmp_dir, filter="data")
        except (tarfile.TarError, OSError):
            return {}
        return _render_variants(Path(tmp_dir), profiles, rebase_to=root)


def _modified_outside_loadout(root: Path, profile: str) -> list[tuple[Path, str, str]] | None:
    """Files matching no output loadout itself could have written — None if unknowable.

    The accept set spans the committed source, the working source, and every declared
    profile, so an unsynced source edit, a synced one and a profile switch all match
    something. Without a committed baseline an unsynced edit is indistinguishable from
    a hand edit, so the caller must not block.
    """
    profiles = declared_profiles(root)
    acceptable = _committed_variants(root, profiles)
    if not acceptable:
        return None
    for path, forms in _render_variants(root, profiles, rebase_to=root).items():
        acceptable.setdefault(path, set()).update(forms)

    modified: list[tuple[Path, str, str]] = []
    for path, expected in render_all(root, profile).items():
        if isinstance(expected, Copied):
            # A copied file has no per-profile form, so it is compared against its
            # source directly. check_all only *reports* drift; this is the guard
            # that stops sync overwriting a hand edit, and it has to cover a
            # supporting file just as much as a SKILL.md.
            if path.is_file() and path.read_bytes() != expected.source.read_bytes():
                modified.append((path, describe_file(path), describe_file(expected.source)))
            continue
        forms = acceptable.get(path, set())
        if not path.is_file() or not forms:
            continue
        actual = path.read_text(encoding="utf-8")
        if _normalise(path, actual) not in forms:
            modified.append((path, actual, expected))
    return modified


def _diff(rel: str, actual: str, expected: str, context: int) -> list[str]:
    return list(
        difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=f"{rel} (on disk)",
            tofile=f"{rel} (expected)",
            n=context,
        )
    )


def cmd_sync(root: Path, profile: str = "default", force: bool = False) -> int:
    if not force:
        modified = _modified_outside_loadout(root, profile)
        if modified is None:
            print("note: no committed baseline — skipping the modified-file check", file=sys.stderr)
        elif modified:
            for path, actual, expected in modified:
                rel = _display(path, root)
                print(f"WARNING: {rel} was modified outside loadout", file=sys.stderr)
                # Tight context: on a 16k settings.json the one runtime-added entry
                # should be readable without scrolling past the whole document.
                lines = _diff(rel, actual, expected, context=1)
                sys.stderr.writelines(lines[:_DIFF_LIMIT])
                if len(lines) > _DIFF_LIMIT:
                    print(f"    ... {len(lines) - _DIFF_LIMIT} more diff line(s)", file=sys.stderr)
            print(
                "\nSync aborted — the '-' lines above exist only on disk and would be lost. "
                "Move them into the source, or run `loadout sync --force` to discard them.",
                file=sys.stderr,
            )
            return 1

    for path in write_all(root, profile):
        print(f"wrote {_display(path, root)}")
    _report_notices(root, profile)
    return 0


def _report_notices(root: Path, profile: str) -> None:
    """Advisory findings, on the same terms as a diverged vendored template.

    A notice describes a source that rendered successfully while doing less than
    it says — a plugin left switched off, a hook that cannot fire. The output is
    correct, so this never moves an exit code; treating it as drift would fail a
    render that did the right thing with what it was given.

    Until this existed the four reports behind it reached nobody, and one was
    visible only by opening the generated JavaScript.
    """
    for notice in collect_notices(root, profile):
        print(f"note: {notice.render()}")


def cmd_check(root: Path, profile: str = "default") -> int:
    drift = check_all(root, profile)
    _report_notices(root, profile)
    # Reported, never failed: check's contract is that generated output matches
    # its source, and a vendored template *is* source — so it falls outside that
    # jurisdiction by definition rather than by exemption (ADR 0014). Saying
    # nothing at all would let a project drift from its template indefinitely,
    # which is the failure vendoring exists to avoid.
    for name in template_divergence(root):
        print(
            f"note: the vendored template {name!r} was modified after it was vendored — "
            f"`loadout template sync {name}` will refuse until those edits go upstream"
        )
    for name in unverifiable_templates(root):
        print(
            f"note: the vendored template {name!r} has no recorded provenance, so nothing "
            f"can tell your edits from its source — `loadout template vendor {name}` takes "
            f"the source wholesale and records one"
        )
    if not drift:
        print("generated files are up to date")
        return 0
    for path, actual, expected in drift:
        rel = _display(path, root)
        print(f"DRIFT: {rel}", file=sys.stderr)
        lines = list(_diff(rel, actual, expected, context=3))
        sys.stderr.writelines(lines[:_DIFF_LIMIT])
        if len(lines) > _DIFF_LIMIT:
            print(f"    ... {len(lines) - _DIFF_LIMIT} more diff line(s)", file=sys.stderr)
    print(
        f"\n{len(drift)} generated file(s) out of sync — run `loadout sync`.",
        file=sys.stderr,
    )
    return 1


def _vendored_state(root: Path, name: str, recorded: str | None) -> str:
    """How a vendored copy stands against the hash recorded when it was vendored."""
    if recorded is None:
        return "vendored, no recorded hash"
    if tree_hash(vendored_path(root, name)) == recorded:
        return "vendored, clean"
    return "vendored, modified"


def cmd_template_list(root: Path) -> int:
    config = load_project_config(project_config_path(root))
    if not config.templates:
        print(
            f"no templates declared — add one with `loadout template add <name>`, "
            f"or list it in {PROJECT_DIR}/{PROJECT_CONFIG_NAME}"
        )
        return 0
    for name in config.templates:
        try:
            found = resolve_template(name, root)
        except LoadoutError as error:
            # Reported rather than raised: `list` is the command you reach for
            # *because* something is wrong, so one broken name must not hide the rest.
            print(f"{name}: unresolved")
            print(f"    {error}")
            continue
        if found.source == VENDORED:
            print(f"{name}: {_vendored_state(root, name, config.vendored_hash(name))}")
        else:
            print(f"{name}: declared, from source {found.source}")
        print(f"    {_display(found.path, root)}")
    return 0


def cmd_template_add(root: Path, name: str) -> int:
    """Declare a template without copying it in — the other first-class mode.

    Resolved before it is written so a name that cannot be found never reaches the
    committed config, where it would fail every later render.
    """
    found = resolve_template(name, root)
    if declare(root, name):
        print(f"declared {name} in {PROJECT_DIR}/{PROJECT_CONFIG_NAME}")
    else:
        print(f"{name} is already declared")
    origin = "the vendored copy" if found.source == VENDORED else f"source {found.source}"
    print(f"resolves from {origin}: {_display(found.path, root)}")
    return 0


def cmd_template_vendor(root: Path, name: str) -> int:
    local = vendored_path(root, name)
    if local.is_dir():
        raise LoadoutError(
            f"{name} is already vendored at {_display(local, root)}; run "
            f"`loadout template sync {name}` to update it"
        )
    found = resolve_template(name, root)
    copy_tree(found.path, local)
    declare(root, name)
    record_hash(root, name, tree_hash(local))
    print(f"vendored {name} from source {found.source} into {_display(local, root)}")
    for relative in template_files(local):
        print(f"    {relative}")
    return 0


def _tree_diff(local: Path, upstream: Path, label: str) -> list[str]:
    """A unified diff per file across both trees, added and removed files included."""
    lines: list[str] = []
    for relative in sorted({*template_files(local), *template_files(upstream)}):
        here, there = local / relative, upstream / relative
        try:
            actual = here.read_text(encoding="utf-8") if here.is_file() else ""
            expected = there.read_text(encoding="utf-8") if there.is_file() else ""
        except UnicodeDecodeError:
            # A template carries whatever a skill carries, binaries included, and
            # a byte diff of one is noise rather than a review.
            if not (here.is_file() and there.is_file()) or here.read_bytes() != there.read_bytes():
                lines.append(f"{label}/{relative}: differs (binary)\n")
            continue
        if actual != expected:
            lines.extend(_diff(f"{label}/{relative}", actual, expected, context=3))
    return lines


def _report_diff(lines: list[str]) -> None:
    sys.stderr.writelines(lines[:_DIFF_LIMIT])
    if len(lines) > _DIFF_LIMIT:
        print(f"    ... {len(lines) - _DIFF_LIMIT} more diff line(s)", file=sys.stderr)


def cmd_template_sync(root: Path, name: str) -> int:
    """Update a vendored copy from its source, refusing rather than merging.

    Refuse-and-diff is never wrong and never silently mangles anything. The
    alternative — a three-way merge against the version you vendored — is the
    largest single piece of work in this design, and the recorded hash is exactly
    the base it would need, so deferring it costs no state migration.
    """
    config = load_project_config(project_config_path(root))
    local = vendored_path(root, name)
    if not local.is_dir():
        raise LoadoutError(
            f"{name} is not vendored, so there is nothing to sync — it resolves from a "
            f"source on every render. Run `loadout template vendor {name}` to copy it in."
        )

    recorded = config.vendored_hash(name)
    current = tree_hash(local)
    # A vendored copy resolves ahead of every source, so the upstream has to be
    # reached past it deliberately.
    upstream = resolve_item(declared_sources(), name, TEMPLATES).path

    # Refuse unless the copy can be *proved* unmodified, rather than refusing only
    # when it can be proved modified. Those differ exactly when there is no
    # provenance to compare against — which is the state `harness add` produced —
    # and fail-open there would let a command whose contract is refuse-rather-than-
    # merge silently overwrite local edits. Matching upstream is proof enough, so a
    # clean copy still falls through to the self-heal below and is never refused.
    if recorded is None and tree_hash(upstream) != current:
        print(
            f"WARNING: the vendored copy of {name} has no recorded provenance",
            file=sys.stderr,
        )
        _report_diff(_tree_diff(local, upstream, name))
        print(
            f"\nSync refused — with no recorded hash, nothing can tell your edits from "
            f"the source's, so the '-' lines above may be either. Commit your copy first "
            f"if you want to keep them, or delete {_display(local, root)} and run "
            f"`loadout template vendor {name}` to take the source wholesale.",
            file=sys.stderr,
        )
        return 1

    if recorded is not None and current != recorded:
        print(
            f"WARNING: the vendored copy of {name} was modified after it was vendored",
            file=sys.stderr,
        )
        _report_diff(_tree_diff(local, upstream, name))
        print(
            f"\nSync refused — the '-' lines above exist only in your copy and would be "
            f"lost. Move them upstream, or delete {_display(local, root)} and run "
            f"`loadout template vendor {name}` to take the upstream wholesale.",
            file=sys.stderr,
        )
        return 1

    # **Position is deliberate: this must stay below both refusals.** It reads
    # like a cheap early-out that belongs at the top, and hoisting it changes a
    # real case — a copy whose recorded hash says modified but whose content now
    # equals the upstream currently refuses, and would start reporting "up to
    # date" instead. Nothing asked for that. The no-provenance gate above already
    # falls through to here when the copy matches, which is the self-heal.
    if tree_hash(upstream) == current:
        print(f"{name} is up to date")
        if recorded is None:
            record_hash(root, name, current)
        return 0

    changed = _tree_diff(local, upstream, name)
    copy_tree(upstream, local)
    record_hash(root, name, tree_hash(local))
    print(
        f"updated {name} from source, {sum(1 for c in changed if c.startswith('---'))} file(s) changed"
    )
    _report_diff(changed)
    return 0


def cmd_explain(root: Path, name: str) -> int:
    root_manifest = manifest_path(root)
    if not root_manifest.is_file() and project_config_path(root).is_file():
        raise LoadoutError(
            f"explain covers instruction fragments, which are global scope only "
            f"({MANIFEST_NAME}); this repo has project scope only "
            f"({PROJECT_DIR}/{PROJECT_CONFIG_NAME})."
        )
    manifest = load_manifest(root_manifest)
    item = resolve_fragment(manifest.sources, name)

    def label(target: InstructionTarget) -> str:
        if target.path is not None:
            return str(target.path)
        return f"destinations={', '.join(str(d) for d in target.destinations)}"

    users: list[str] = []
    unresolved: list[str] = []
    for target in manifest.targets:
        matched = False
        for fragment in target.fragments:
            try:
                if resolve_fragment(manifest.sources, fragment).path == item.path:
                    matched = True
            except LoadoutError:
                unresolved.append(f"{label(target)}: {fragment}")
        if matched:
            users.append(label(target))

    print(f"{item.name}")
    print(f"  source: {item.source}")
    print(f"  file:   {item.path}")
    if users:
        print("  used by:")
        for target_path in users:
            print(f"    {target_path}")
    else:
        print("  used by: (no target lists it)")
    if unresolved:
        print("  warning: other fragments in this manifest do not resolve:", file=sys.stderr)
        for entry in unresolved:
            print(f"    {entry}", file=sys.stderr)
    return 0
