from __future__ import annotations

from pathlib import Path

from .errors import LoadoutError
from .manifest import InstructionTarget, Manifest
from .resolve import resolve_fragment

# States a consequence, not a prohibition. "do not edit" is a rule, and an
# instruction file is loaded into a session's context next to the project's own
# AGENTS.md — where a rule with no stated scope gets lifted out and applied to
# the wrong file. That happened. A consequence cannot be generalised, and the
# last clause names the ambiguity outright.
HEADER = (
    "<!-- Generated by loadout from instructions/. Edits to this file are replaced "
    "on the next sync; other AGENTS.md and CLAUDE.md files are unaffected. -->"
)


def load_fragment(path: Path) -> str:
    if not path.is_file():
        raise LoadoutError(f"fragment not found: {path}")
    return path.read_text(encoding="utf-8").strip()


def render(target: InstructionTarget, manifest: Manifest) -> str:
    swaps = dict(target.substitute)
    blocks = [HEADER]
    for name in target.fragments:
        item = resolve_fragment(manifest.sources, swaps.get(name, name))
        blocks.append(load_fragment(item.path))
    return "\n\n".join(blocks) + "\n"
