from __future__ import annotations

from pathlib import Path

from .errors import LoadoutError
from .manifest import InstructionTarget, Manifest
from .resolve import INSTRUCTIONS, resolve_item

HEADER = (
    "<!-- GENERATED by loadout — do not edit. "
    "Edit the fragments in instructions/ and re-run `loadout sync`. -->"
)


def load_fragment(path: Path) -> str:
    if not path.is_file():
        raise LoadoutError(f"fragment not found: {path}")
    return path.read_text(encoding="utf-8").strip()


def render(target: InstructionTarget, manifest: Manifest) -> str:
    blocks = [HEADER]
    for name in target.fragments:
        item = resolve_item(manifest.sources, name, INSTRUCTIONS, manifest.variants)
        blocks.append(load_fragment(item.path))
    return "\n\n".join(blocks) + "\n"
