from __future__ import annotations

import copy
from collections.abc import Mapping
from typing import Any

import tomlkit

from .errors import LoadoutError

__all__ = [
    "MARKETPLACES",
    "PLUGINS",
    "marketplaces",
    "plugins",
    "render_claude_plugins",
    "render_codex_plugins",
    "render_pi_plugins",
    "unaddressable",
    "unregistered_marketplaces",
]

# A plugin is two things — content on disk, and a declaration that it is switched
# on. This slice owns the second only: loadout never clones, fetches, installs or
# registers, exactly as with the global source (ADR 0010) and templates.
#
# The document is two maps rather than plugin names at top level, so a
# marketplace can be declared without a plugin called `marketplaces` colliding
# with it:
#
#     {"marketplaces": {"<name>": {…}},
#      "plugins": {"<name>": {"source": …, "marketplace": …, "pi": {…}}}}
PLUGINS = "plugins"
MARKETPLACES = "marketplaces"

SECTIONS = (MARKETPLACES, PLUGINS)

# `source` and `marketplace` are **loadout's** vocabulary — the portable unit
# this slice invented — so a key outside them is a typo and is refused. A plugin
# that silently fails to render is a plugin the user believes is on and is not.
#
# The nested blocks are the opposite case and are passed through untouched: `pi`
# holds Pi's own per-package filters and a `[marketplaces.x]` table holds Codex's
# own registration keys. We do not have either schema, so the harness decides —
# the lesson `render_claude_hooks` records, where validation invented from one
# machine's files was falsified by the first sample of a survey.
REFERENCE_KEYS = frozenset({"source", "marketplace", "pi"})

# What each harness needs before it can name a plugin at all. Claude and Codex
# converged independently on `<name>@<marketplace>`; Pi has no marketplace
# concept and addresses a package by where it comes from.
ADDRESSED_BY = {"claude": "marketplace", "codex": "marketplace", "pi": "source"}

HEADER_LINES = (
    "Generated by loadout from plugins fragments.",
    "Edits to this file are replaced on the next sync.",
)


def _section(document: Mapping[str, Any], name: str) -> dict[str, Any]:
    stray = [key for key in document if key not in SECTIONS]
    if stray:
        raise LoadoutError(
            f"plugins: unknown section(s) {', '.join(stray)}; a plugins fragment holds "
            f"{' and '.join(SECTIONS)}, each a map keyed by name"
        )
    block = document.get(name, {})
    if not isinstance(block, Mapping):
        raise LoadoutError(f"plugins: {name} must be a map of name -> table")
    for key, entry in block.items():
        if not isinstance(entry, Mapping):
            raise LoadoutError(f"plugins: {name}.{key} must be a table")
    return {key: dict(entry) for key, entry in block.items()}


def plugins(document: Mapping[str, Any]) -> dict[str, dict[str, Any]]:
    """The document's plugin references, validated, in declaration order."""
    references = _section(document, PLUGINS)
    for name, reference in references.items():
        stray = sorted(key for key in reference if key not in REFERENCE_KEYS)
        if stray:
            known = ", ".join(sorted(REFERENCE_KEYS))
            raise LoadoutError(
                f"plugins: {name} has unknown key(s) {', '.join(stray)} (known: {known})"
            )
        for key in ("source", "marketplace"):
            if key in reference and not isinstance(reference[key], str):
                raise LoadoutError(f"plugins: {name}.{key} must be a string")
    return references


def marketplaces(document: Mapping[str, Any]) -> dict[str, dict[str, Any]]:
    return _section(document, MARKETPLACES)


def unaddressable(document: Mapping[str, Any], harness: str) -> tuple[str, ...]:
    """Plugins this harness has no way to name, as `"<name>: no <key>"`.

    Skipped rather than refused, and the two halves of the reason differ. A
    marketplace-only reference cannot be rendered for Pi and a source-only one
    cannot be rendered for Claude, so a set spanning both harnesses would fail
    entirely if either were an error — and the mixed set is the ordinary case,
    not a corner one.

    Skipping also fails **safe**: the plugin is simply not switched on, which is
    where it was before. Contrast `_reject_foreign_variables` in the hooks slice,
    which refuses because its failure denies tool calls.
    """
    key = ADDRESSED_BY[harness]
    return tuple(f"{name}: no {key}" for name, ref in plugins(document).items() if key not in ref)


def unregistered_marketplaces(
    document: Mapping[str, Any], known: frozenset[str]
) -> tuple[str, ...]:
    """Marketplaces this document names that `known` does not carry, in order.

    `known` is a parameter because the answer differs by harness and neither
    source is a file a renderer may read (ADR 0001). Claude keeps its registry in
    `~/.claude/plugins/known_marketplaces.json`, which carries `lastUpdated`
    timestamps and `installLocation` paths — machine state loadout must not
    render (ADR 0008) — so there it reports and the user runs the add command.
    Codex keeps registration in `config.toml`, which loadout writes, so there the
    same call answers "declared in the source?" instead.
    """
    named = [ref["marketplace"] for ref in plugins(document).values() if "marketplace" in ref]
    return tuple(dict.fromkeys(name for name in named if name not in known))


def _addressable(document: Mapping[str, Any], harness: str) -> dict[str, dict[str, Any]]:
    key = ADDRESSED_BY[harness]
    return {name: ref for name, ref in plugins(document).items() if key in ref}


def render_claude_plugins(document: Mapping[str, Any]) -> dict[str, bool]:
    """Claude's `enabledPlugins` value, keyed `<name>@<marketplace>`.

    The caller writes it into `settings.json`, which this slice shares with
    settings, permissions and hooks; plugins owns only this key.

    Every entry is `true`, because presence *is* enablement here: a profile takes
    a plugin out with a `null` in an overlay fragment, which `merge_documents`
    removes before this ever sees it. Whether Claude also honours `false` is not
    something this machine can settle, and nothing needs it to.
    """
    return {
        f"{name}@{ref['marketplace']}": True
        for name, ref in _addressable(document, "claude").items()
    }


def render_pi_plugins(document: Mapping[str, Any]) -> list[Any]:
    """Pi's `packages` value: a source string, or an object carrying its filters.

    Both forms are Pi's own (`docs/packages.md`, shipped with 0.84.1): the string
    loads every resource a package offers, the object narrows it with `skills`,
    `extensions`, `prompts` and `themes` lists. The object is emitted only when
    the fragment asks for one, so a plain reference stays a plain string.

    That filter map is the reason a `pi` block exists at all. `~/.pi/agent/
    settings.json` carries `{"source": "git:github.com/obra/superpowers",
    "extensions": []}` — a package kept for its skills with its extension muted,
    because that extension injected a bootstrap block into every session. A
    portable representation that flattened enablement to on/off would lose a
    lever the user actually reached for.
    """
    entries: list[Any] = []
    for ref in _addressable(document, "pi").values():
        options = ref.get("pi") or {}
        entries.append(
            {"source": ref["source"], **copy.deepcopy(options)} if options else ref["source"]
        )
    return entries


def render_codex_plugins(document: Mapping[str, Any]) -> str:
    """Codex's plugin enablement and marketplace registration, as TOML.

    Codex addresses a plugin exactly as Claude does — `<name>@<marketplace>` —
    which is the one convergence this project has found outside a published
    standard. It differs in keeping the marketplace registration in the same file
    loadout writes, so `[marketplaces.<name>]` renders here rather than being
    reported.

    A marketplace is emitted only when a rendered plugin names it: registering
    one nothing uses would put a path into Codex's config that no plugin reaches
    through. One a plugin names but the source does not declare is left to
    whatever registered it by hand, and `unregistered_marketplaces` is how a
    caller finds out.
    """
    references = _addressable(document, "codex")
    declared = marketplaces(document)
    used = dict.fromkeys(ref["marketplace"] for ref in references.values())

    rendered = tomlkit.document()
    for line in HEADER_LINES:
        rendered.add(tomlkit.comment(line))

    registrations = tomlkit.table(is_super_table=True)
    for name in used:
        if name in declared:
            block = tomlkit.table()
            for key, value in declared[name].items():
                block[key] = value
            registrations[name] = block
    if len(registrations) > 0:
        rendered[MARKETPLACES] = registrations

    enabled = tomlkit.table(is_super_table=True)
    for name, ref in references.items():
        block = tomlkit.table()
        block["enabled"] = True
        enabled[f"{name}@{ref['marketplace']}"] = block
    if len(enabled) > 0:
        rendered[PLUGINS] = enabled

    return tomlkit.dumps(rendered)
