"""MCP server definitions — where a server lives and how to reach it.

Distinct from the `mcp-permissions` slice, which renders *which tools may be
called* from permissions.toml's [mcp] section. The two share a word and nothing
else; conflating them has produced two recorded wrong conclusions, so this
module never touches Rules and that one never reads this file.
"""

from __future__ import annotations

import json
import tomllib
from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .errors import LoadoutError

__all__ = [
    "SERVERS_SOURCE",
    "Server",
    "is_http",
    "parse_servers",
    "render_claude_servers",
    "render_codex_servers",
    "render_opencode_servers",
    "render_pi_servers",
]

SERVERS_SOURCE = "mcp.toml"
TRANSPORTS = ("http", "stdio")

HEADER_LINES = (
    "Generated by loadout from mcp.toml.",
    "Edits to this file are replaced on the next sync.",
)

# Rejected rather than ignored, because the failure is silent and shaped like a
# security bug: `auth_env_varr` parses fine, yields no auth var, and renders a
# server that connects unauthenticated with nothing saying so. `plugins.py`
# rejects stray keys for the same reason.
SERVER_KEYS = frozenset({"transport", "url", "auth_env_var", "command", "args", "env"})


@dataclass(frozen=True)
class Server:
    name: str
    transport: str
    url: str | None = None
    auth_env_var: str | None = None
    command: str | None = None
    args: tuple[str, ...] = ()
    env: Mapping[str, str] = field(default_factory=dict)


def is_http(server: Server) -> bool:
    return server.transport == "http"


def parse_servers(path: Path) -> dict[str, Server]:
    """Every server the file declares, in declaration order.

    Absent file means no servers, not an error: a source that offers no
    definitions contributes none, exactly as one offering no permissions.toml
    contributes no tier.
    """
    if not path.is_file():
        return {}
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError as error:
        raise LoadoutError(f"{path}: invalid TOML: {error}") from error

    servers: dict[str, Server] = {}
    for name, spec in data.items():
        if not isinstance(spec, dict):
            raise LoadoutError(f"{path}: [{name}] must be a table")
        stray = sorted(set(spec) - SERVER_KEYS)
        if stray:
            raise LoadoutError(
                f"{path}: [{name}] unknown key(s) {', '.join(stray)} "
                f"(a server takes: {', '.join(sorted(SERVER_KEYS))})"
            )
        transport = spec.get("transport")
        if transport not in TRANSPORTS:
            raise LoadoutError(
                f"{path}: [{name}] unknown transport {transport!r} "
                f"(expected one of {', '.join(TRANSPORTS)})"
            )
        # Validated here rather than in four renderers: each would fail
        # differently, and three of them only when that harness is enabled.
        if transport == "http" and not spec.get("url"):
            raise LoadoutError(f"{path}: [{name}] transport is http, so it needs a url")
        if transport == "stdio" and not spec.get("command"):
            raise LoadoutError(f"{path}: [{name}] transport is stdio, so it needs a command")
        servers[name] = Server(
            name=name,
            transport=transport,
            url=spec.get("url"),
            auth_env_var=spec.get("auth_env_var"),
            command=spec.get("command"),
            args=tuple(spec.get("args", ())),
            env=dict(spec.get("env", {})),
        )
    return servers


def _toml_string(value: str) -> str:
    return json.dumps(value)


def _toml_array(values: tuple[str, ...]) -> str:
    return "[" + ", ".join(_toml_string(v) for v in values) + "]"


# --------------------------------------------------------------------------
# claude — .mcp.json (project) / the staged document `claude mcp add-json`
# consumes (global): the exact per-server shape that command takes, which is
# also how Claude stores a server once added. Header interpolation is ${VAR}.
# --------------------------------------------------------------------------


def render_claude_servers(servers: dict[str, Server]) -> dict[str, Any]:
    config: dict[str, Any] = {}
    for name, server in servers.items():
        entry: dict[str, Any]
        if is_http(server):
            assert server.url is not None
            entry = {"type": "http", "url": server.url}
            if server.auth_env_var:
                entry["headers"] = {"Authorization": f"Bearer ${{{server.auth_env_var}}}"}
        else:
            assert server.command is not None
            entry = {
                "type": "stdio",
                "command": server.command,
                "args": list(server.args),
                "env": dict(server.env),
            }
        config[name] = entry
    return config


# --------------------------------------------------------------------------
# codex — [mcp_servers.<name>] tables. Header comment guards the staged copy
# only; the caller merges this into Codex's config through tomllib, which
# drops the comment.
# --------------------------------------------------------------------------


def render_codex_servers(servers: dict[str, Server]) -> str:
    lines = [f"# {line}" for line in HEADER_LINES]
    for name, server in servers.items():
        lines.append("")
        lines.append(f"[mcp_servers.{name}]")
        if is_http(server):
            assert server.url is not None
            lines.append(f"url = {_toml_string(server.url)}")
            if server.auth_env_var:
                lines.append(f"bearer_token_env_var = {_toml_string(server.auth_env_var)}")
        else:
            assert server.command is not None
            lines.append(f"command = {_toml_string(server.command)}")
            if server.args:
                lines.append(f"args = {_toml_array(server.args)}")
            variables = dict(server.env)
            if variables:
                lines.append("")
                lines.append(f"[mcp_servers.{name}.env]")
                for key in sorted(variables):
                    lines.append(f"{key} = {_toml_string(variables[key])}")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# opencode — the `mcp` key's value, one key of a document `permission` also
# owns. A local server takes one `command` array combining command and args,
# not separate fields, and interpolation is {env:VAR} rather than ${VAR}.
# --------------------------------------------------------------------------


def render_opencode_servers(servers: dict[str, Server]) -> dict[str, Any]:
    mcp: dict[str, Any] = {}
    for name, server in servers.items():
        entry: dict[str, Any]
        if is_http(server):
            assert server.url is not None
            entry = {"type": "remote", "url": server.url}
            if server.auth_env_var:
                entry["headers"] = {"Authorization": f"Bearer {{env:{server.auth_env_var}}}"}
        else:
            assert server.command is not None
            entry = {"type": "local", "command": [server.command, *server.args]}
            variables = dict(server.env)
            if variables:
                entry["environment"] = variables
        mcp[name] = entry
    return mcp


# --------------------------------------------------------------------------
# pi — `mcpServers`, the shape pi-mcp-adapter's ServerEntry takes. HTTP auth
# uses `bearerTokenEnv` (the variable NAME; the adapter reads it at call
# time), so no token is ever written here.
# --------------------------------------------------------------------------


def render_pi_servers(servers: dict[str, Server]) -> dict[str, Any]:
    entries: dict[str, Any] = {}
    for name, server in servers.items():
        entry: dict[str, Any]
        if is_http(server):
            assert server.url is not None
            entry = {"url": server.url}
            if server.auth_env_var:
                entry["bearerTokenEnv"] = server.auth_env_var
        else:
            assert server.command is not None
            entry = {"command": server.command, "args": list(server.args)}
            variables = dict(server.env)
            if variables:
                entry["env"] = variables
        entries[name] = entry
    return {"mcpServers": entries}
