"""The skills slice — the first unit that is a directory rather than a document.

Only `SKILL.md` is composed; every other file in the tree is carried across
byte-for-byte with its relative path preserved (spec 4a §1). The dominant case by
a wide margin is the same bytes everywhere — 49 of 50 skills in the live source
vary not at all — so every mechanism here has to cost nothing until it is used.
That is why an unmarked document round-trips through composition unchanged rather
than being parsed and re-emitted.
"""

from __future__ import annotations

import re
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path

from .errors import LoadoutError
from .project import KNOWN_HARNESSES

SKILL_DOCUMENT = "SKILL.md"

BANNER = (
    "<!-- Generated by loadout from skills/{name}/. Edits here are replaced on the next sync. -->"
)

# Directories that are build output or version control, never skill content. A
# skill vendoring node_modules would otherwise be copied into every harness.
EXCLUDED_DIRECTORIES = frozenset(
    {
        "__pycache__",
        ".git",
        ".hg",
        "node_modules",
        ".venv",
        ".mypy_cache",
        ".ruff_cache",
        ".pytest_cache",
    }
)
EXCLUDED_SUFFIXES = (".pyc", ".pyo", ".swp")
EXCLUDED_NAMES = frozenset({".DS_Store"})

_OPEN_MARKER = re.compile(r"^::: *([a-z][a-z0-9 _-]*?) *$")
_CLOSE_MARKER = re.compile(r"^::: *$")
_FENCE = re.compile(r"^\s*(```|~~~)")
_CONCEPT = re.compile(r":([a-z][a-z0-9-]*)\[([^\]]*)\]")
_TOP_LEVEL_KEY = re.compile(r"^([A-Za-z][A-Za-z0-9_-]*):(.*)$")


@dataclass(frozen=True)
class Concept:
    """One inline vocabulary entry and what it becomes per harness.

    The fallback is what makes this more than a naming table: a harness with no
    subagent mechanism gets "do it yourself" rather than a broken instruction.
    """

    expansions: Mapping[str, str]
    fallback: str | None = None

    def expand(self, harness: str, argument: str, name: str) -> str:
        template = self.expansions.get(harness, self.fallback)
        if template is None:
            raise LoadoutError(
                f"concept {name!r} has no expansion for {harness} and no fallback — "
                f"add one to the concept table or mark the section instead"
            )
        return template.replace("{}", argument)


# Starts empty and grows only against demonstrated need (spec 4a, out of scope).
# The mechanism is the deliverable; the vocabulary is not invented up front.
CONCEPTS: dict[str, Concept] = {}


@dataclass(frozen=True)
class Skill:
    name: str
    document: Path
    supporting: tuple[Path, ...]
    """Paths relative to the skill directory, sorted, excluding SKILL.md."""


def _excluded(path: Path, relative: Path) -> bool:
    if any(part in EXCLUDED_DIRECTORIES for part in relative.parts):
        return True
    return path.name in EXCLUDED_NAMES or path.suffix in EXCLUDED_SUFFIXES


def discover_skills(skills_root: Path) -> tuple[Skill, ...]:
    """Every directory holding a SKILL.md, in sorted order.

    A directory is the declaration: no manifest entry, no marker (spec 1 §4). A
    subdirectory without SKILL.md is not a skill and is skipped rather than
    reported, so a stray directory cannot fail a sync.
    """
    if not skills_root.is_dir():
        return ()
    skills: list[Skill] = []
    for entry in sorted(skills_root.iterdir()):
        document = entry / SKILL_DOCUMENT
        if not entry.is_dir() or not document.is_file():
            continue
        supporting = tuple(
            sorted(
                item.relative_to(entry)
                for item in entry.rglob("*")
                if item.is_file()
                and item != document
                and not _excluded(item, item.relative_to(entry))
            )
        )
        skills.append(Skill(name=entry.name, document=document, supporting=supporting))
    return tuple(skills)


def split_frontmatter(text: str) -> tuple[list[str] | None, str]:
    """Frontmatter lines and the body, or (None, text) when there is none.

    Every harness requires the opening `---` on line 1, so anything else means
    the document has no frontmatter rather than malformed frontmatter.
    """
    if not text.startswith("---\n"):
        return None, text
    lines = text.split("\n")
    for index in range(1, len(lines)):
        if lines[index] == "---":
            return lines[1:index], "\n".join(lines[index + 1 :])
    raise LoadoutError("frontmatter opened with --- but never closed")


def apply_frontmatter(lines: list[str], harness: str) -> list[str]:
    """Merge the harness's override block over the shared keys and drop every block.

    Frontmatter is YAML and a `:::` fence in it would be parsed as data, so
    per-harness *values* need a structured selector rather than a marked section.
    Absent any harness block — 49 of 50 skills — the lines pass through
    untouched, which is what keeps the shared case free.
    """
    overrides: dict[str, str] = {}
    block_ranges: list[tuple[int, int]] = []
    index = 0
    while index < len(lines):
        match = _TOP_LEVEL_KEY.match(lines[index])
        if match and match.group(1) in KNOWN_HARNESSES and not match.group(2).strip():
            start = index
            index += 1
            while index < len(lines) and (not lines[index].strip() or lines[index][:1].isspace()):
                if match.group(1) == harness:
                    child = _TOP_LEVEL_KEY.match(lines[index].strip())
                    if child:
                        overrides[child.group(1)] = child.group(2)
                index += 1
            block_ranges.append((start, index))
            continue
        index += 1

    dropped = {position for start, end in block_ranges for position in range(start, end)}
    result: list[str] = []
    for position, line in enumerate(lines):
        if position in dropped:
            continue
        match = _TOP_LEVEL_KEY.match(line)
        if match and match.group(1) in overrides:
            result.append(f"{match.group(1)}:{overrides.pop(match.group(1))}")
            continue
        result.append(line)
    # An override naming a key the shared block never defined still has to land.
    result.extend(f"{key}:{value}" for key, value in overrides.items())
    return result


def apply_body(body: str, harness: str, skill: str) -> str:
    """Resolve marked sections and inline concepts, leaving code fences alone.

    A marker wraps whole blocks and never sits inside one: markers inside a
    fenced code block are content, and rewriting them would corrupt the example
    a skill is trying to show.
    """
    lines = body.split("\n")
    result: list[str] = []
    in_fence = False
    keeping: list[bool] = []
    for line in lines:
        if _FENCE.match(line):
            in_fence = not in_fence
            if all(keeping):
                result.append(line)
            continue
        if not in_fence:
            opening = _OPEN_MARKER.match(line)
            if opening:
                named = opening.group(1).split()
                unknown = sorted(set(named) - KNOWN_HARNESSES)
                if unknown:
                    raise LoadoutError(
                        f"{skill}/SKILL.md: unknown harness(es) {', '.join(unknown)} in "
                        f"a ::: marker (known: {', '.join(sorted(KNOWN_HARNESSES))})"
                    )
                keeping.append(harness in named)
                continue
            if _CLOSE_MARKER.match(line):
                if not keeping:
                    raise LoadoutError(f"{skill}/SKILL.md: ::: closes a section that never opened")
                keeping.pop()
                continue
        if all(keeping):
            result.append(_expand_line(line, harness) if not in_fence else line)
    if keeping:
        raise LoadoutError(f"{skill}/SKILL.md: a ::: section was opened and never closed")
    return "\n".join(result)


def _expand_line(line: str, harness: str) -> str:
    def replace(match: re.Match[str]) -> str:
        name = match.group(1)
        concept = CONCEPTS.get(name)
        if concept is None:
            return match.group(0)
        return concept.expand(harness, match.group(2), name)

    return _CONCEPT.sub(replace, line)


def render_skill(skill: Skill, harness: str) -> str:
    text = skill.document.read_text(encoding="utf-8")
    frontmatter, body = split_frontmatter(text)
    banner = BANNER.format(name=skill.name)
    resolved = apply_body(body, harness, skill.name)
    if frontmatter is None:
        # No frontmatter to sit under, so the banner leads.
        return f"{banner}\n{resolved}"
    merged = apply_frontmatter(frontmatter, harness)
    # Below the closing ---, never above it: a banner on line 1 leaves the
    # frontmatter unparsed and the skill then shows the banner as its
    # description. Already hit once in ~/ac/skills/sync.py.
    return "---\n" + "\n".join(merged) + "\n---\n\n" + banner + "\n" + resolved
