from __future__ import annotations

from dataclasses import dataclass
from pathlib import PurePosixPath

HEADER = (
    "<!-- GENERATED by loadout — do not edit. "
    "Edit the fragments in global/fragments/ and re-run `loadout sync`. -->"
)

_CLAUDE_INTRO = """# Global CLAUDE.md

User-scoped guidance that applies to every Claude Code session on this machine. Loaded from `~/.claude/CLAUDE.md` (symlinked to this file).

Keep this file **project-agnostic** — anything specific to a particular repo belongs in that repo's own `CLAUDE.md`."""

_SHARED_INTRO = """# Global agent instructions

User-scoped guidance that applies to every agent session on this machine. Installed to `~/.codex/AGENTS.md` (Codex), `~/.gemini/GEMINI.md` (Antigravity `agy`), and `~/.pi/agent/AGENTS.md` (Pi).

Keep this file **project-agnostic** — anything specific to a particular repo belongs in that repo's own `AGENTS.md`."""

_COMMON_TAIL = ("video-content", "browser-automation", "secrets")
_POLICY_TAIL = ("git-commit-policy", "working-style")


@dataclass(frozen=True)
class Target:
    """One generated instruction file and where it is deployed."""

    path: PurePosixPath
    intro: str
    fragments: tuple[str, ...]
    destinations: tuple[PurePosixPath, ...]
    profile: str | None = None


TARGETS: tuple[Target, ...] = (
    Target(
        path=PurePosixPath("claude/CLAUDE.md"),
        intro=_CLAUDE_INTRO,
        fragments=("web-fetching", *_COMMON_TAIL, "git-policy", *_POLICY_TAIL),
        destinations=(PurePosixPath("~/.claude/CLAUDE.md"),),
        profile=None,
    ),
    Target(
        path=PurePosixPath("claude/CLAUDE.autonomous.md"),
        intro=_CLAUDE_INTRO,
        fragments=("web-fetching", *_COMMON_TAIL, "git-policy.autonomous", *_POLICY_TAIL),
        destinations=(PurePosixPath("~/.claude/CLAUDE.md"),),
        profile="autonomous",
    ),
    Target(
        path=PurePosixPath("global/AGENTS.md"),
        intro=_SHARED_INTRO,
        fragments=("web-fetching.shared", *_COMMON_TAIL, "git-policy", *_POLICY_TAIL),
        destinations=(
            PurePosixPath("~/.codex/AGENTS.md"),
            PurePosixPath("~/.gemini/GEMINI.md"),
            PurePosixPath("~/.pi/agent/AGENTS.md"),
        ),
        profile=None,
    ),
)
