"""What `sync` last wrote, per destination — ADR 0008's deferred sidecar.

The guard in `commands.py` asks "could loadout have written this file?" and answers
it from two renders: the committed source and the working tree now. ADR 0008 accepted
that as "correct, at the cost of warning benignly on first adoption and on a
reverted-but-already-synced edit", and deferred a record of what was actually written
until orphan removal forced it.

The cost turned out larger than that estimate. Two cases it does not name: editing a
source twice before committing leaves an output rendered from a state that is neither
baseline, and a skill's supporting file has no accept set at all, so the first edit
blocks every later sync until `--force`. This module supplies the missing third
variant. Orphan removal is the next consumer, which is why entries are retained rather
than pruned: a destination loadout no longer renders is exactly what that needs.

**It only ever widens acceptance.** Every check is `entry is not None and the hash
matches`, so a missing, corrupt or version-bumped record reproduces the two-variant
behaviour exactly. There is no path where a hand edit is accepted because state was
lost — losing state fails closed.
"""

from __future__ import annotations

import hashlib
import json
import re
from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .machine import machine_state_dir

VERSION = 1

_BANNER_LINE = re.compile(
    r"^\s*(?:<!--\s*|#\s*|//\s*)generated by loadout\b.*$", re.MULTILINE | re.IGNORECASE
)
_BLANK_RUN = re.compile(r"\n{3,}")
_BANNER_CONTINUATION = re.compile(
    r"^\s*(?:#|//)\s*edits? to this file are replaced.*$"
    r"|^\s*(?:#|//)\s*edit permissions\.toml\b.*$",
    re.MULTILINE | re.IGNORECASE,
)


def normalise(path: Path, content: str) -> str:
    """Key order is load-bearing in output, but not in the question 'who wrote this?'.

    Claude Code rewrites its own settings.json and reorders keys loadout owns; comparing
    the parsed document keeps that from reading as a hand edit.

    The banner comes out for the same reason. It is loadout's own text, so rewording it
    is not evidence a user touched the file — but without this, changing it makes every
    generated file on disk differ from every acceptable variant at once, and the guard
    reports the whole tree as hand-edited. It did, on 205 files.

    Lives here rather than in `commands.py` because the write side and the guard must
    agree on it exactly: a recorded hash is worthless if the two normalise differently.
    """
    if path.suffix != ".json":
        stripped = _BANNER_CONTINUATION.sub("", _BANNER_LINE.sub("", content))
        # Removing the banner leaves the blank line that separated it, so a file
        # with no banner and one with a banner still differ by an interior blank
        # — which `.strip()` cannot reach. Collapsing runs is what makes the two
        # actually compare equal, and without it the guard reports a banner-only
        # difference as a hand edit. It did, on the one skill that carries a
        # `::: opencode` section.
        return _BLANK_RUN.sub("\n\n", stripped).strip()
    try:
        return json.dumps(json.loads(content), sort_keys=True)
    except json.JSONDecodeError:
        return content


@dataclass(frozen=True)
class WrittenEntry:
    """One destination as `sync` left it.

    `norm_sha256` is what the guard compares, because a harness reordering keys in a
    file it shares with loadout is not a hand edit. `sha256` is the raw bytes, which is
    what a copied file is compared by and what orphan removal will want.

    A merged destination carries **no hash**: the applied document embeds bytes the
    harness owns and may rewrite a second later, so a hash of it would go stale without
    anything having gone wrong. `owned` is recorded instead — the key names orphan
    removal must strip rather than deleting a file loadout does not own.
    """

    kind: str
    sha256: str | None = None
    norm_sha256: str | None = None
    executable: bool = False
    owned: tuple[str, ...] = ()


def _digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def written_state_path(root: Path, env: Mapping[str, str] | None = None) -> Path:
    """One record per root, named by the root's resolved path.

    Keyed by a hash rather than the path itself so the name is filesystem-safe; the
    path is stored inside the file so it stays inspectable by hand.
    """
    key = _digest(str(root.resolve()).encode())[:16]
    return machine_state_dir(env) / "written" / f"{key}.json"


def read_written(root: Path, env: Mapping[str, str] | None = None) -> dict[Path, WrittenEntry]:
    """The record, or empty when there is none to be had.

    Absent, unreadable, malformed and version-bumped all mean the same thing to the
    caller: no baseline, behave as before the record existed.
    """
    path = written_state_path(root, env)
    try:
        document = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    if not isinstance(document, dict) or document.get("version") != VERSION:
        return {}
    entries = document.get("written")
    if not isinstance(entries, dict):
        return {}
    out: dict[Path, WrittenEntry] = {}
    for name, raw in entries.items():
        if not isinstance(raw, dict) or not isinstance(raw.get("kind"), str):
            continue
        out[Path(name)] = WrittenEntry(
            kind=raw["kind"],
            sha256=raw.get("sha256"),
            norm_sha256=raw.get("norm_sha256"),
            executable=bool(raw.get("executable", False)),
            owned=tuple(raw.get("owned", ())),
        )
    return out


def record_written(
    root: Path,
    profile: str,
    entries: Mapping[Path, WrittenEntry],
    env: Mapping[str, str] | None = None,
) -> Path | None:
    """Merge this run's writes into the record, keeping what earlier runs wrote.

    Retention is the point, not laziness: a destination this run no longer renders is
    precisely what orphan removal needs to find, and pruning it here would throw that
    away every time a target was deleted.
    """
    path = written_state_path(root, env)
    merged = dict(read_written(root, env))
    merged.update(entries)
    document: dict[str, Any] = {
        "version": VERSION,
        "root": str(root.resolve()),
        "profile": profile,
        "written": {
            str(dest): {
                k: v
                for k, v in {
                    "kind": entry.kind,
                    "sha256": entry.sha256,
                    "norm_sha256": entry.norm_sha256,
                    "executable": entry.executable or None,
                    "owned": list(entry.owned) or None,
                }.items()
                if v is not None
            }
            for dest, entry in sorted(merged.items(), key=lambda item: str(item[0]))
        },
    }
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")
    except OSError:
        # A record that cannot be written degrades to no record, which is the
        # behaviour that existed before it — never a failed sync. The files are
        # already on disk by the time this runs, so raising here would report a
        # completed sync as broken. A sandbox denying the state directory is the
        # case that forced this: the profile may grant the machine config file
        # without granting the directory beside it.
        return None
    return path


def accepts_text(entry: WrittenEntry | None, path: Path, actual: str) -> bool:
    return entry is not None and entry.norm_sha256 == _digest(normalise(path, actual).encode())


def accepts_bytes(entry: WrittenEntry | None, actual: bytes) -> bool:
    return entry is not None and entry.sha256 == _digest(actual)


def text_entry(path: Path, content: str) -> WrittenEntry:
    return WrittenEntry(
        kind="text",
        sha256=_digest(content.encode()),
        norm_sha256=_digest(normalise(path, content).encode()),
    )


def copied_entry(source: Path) -> WrittenEntry:
    data = source.read_bytes()
    return WrittenEntry(
        kind="copied", sha256=_digest(data), executable=bool(source.stat().st_mode & 0o111)
    )


def merged_entry(owned: Iterable[str]) -> WrittenEntry:
    return WrittenEntry(kind="merged", owned=tuple(sorted(owned)))
